name: gethome
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.6
  http: ^1.1.0

  # Image and media handling
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0
  carousel_slider: ^4.2.1

  # Maps and location (removed problematic location package)
  google_maps_flutter: ^2.2.8
  geolocator: ^9.0.2
  permission_handler: ^11.0.1
  geocoding: ^2.1.0

  # Storage and preferences
  shared_preferences: ^2.2.0

  # UI and utilities
  intl: ^0.18.1
  url_launcher: ^6.1.12
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

